### PR TITLE
Migration of build pipeline to GitHub actions

### PR DESCRIPTION
**Pull request by stefancyliax**
Migration of build pipeline to Github Actions from TravisCI

- Pipeline was migrated to Github Actions
- Protobuf updated to current version

### CODE REVIEW

**Comment by stefancyliax** [comment]
@pmai @kmeids @engelben 
Who can review this?

**Comment by kmeids** [comment]
**Output CCB 28.04.2021:**
1. @ThomasNaderBMW will take a look on it.

**Comment by ThomasNaderBMW** [comment]
@stefancyliax : We will see if the build pipeline works after merging this PR, right? We could then test the PR from Thomas Bleher?

**Comment by stefancyliax** [comment]
@ThomasNaderBMW The behavior is a bit weird here. Since I made an external PR (from my fork), the pipeline is not run within this PR.
But you can take a look at my fork: https://github.com/stefancyliax/osi-visualizer/actions/workflows/ci-build.yml

**Review by pmai — APPROVED** [review]

**Pull request merged**
