### PR TITLE
Properly rebuild resource file if shader changes (#53)

### PR DESCRIPTION
**Pull request by tbleher**
Unfortunately CMAKE_AUTORCC does not properly add dependencies on the
files included by the qrc file. This means that when a file changes that
is included in the qrc file, the qrc file is not automatically rebuilt.
This results in broken builds.

Fix this by building the qrc file directly (instead of relying on
CMAKE_AUTORCC) and adding proper dependencies.

As a side cleanup, move the resources.qrc file to resources/, so the
top-level directory is cleaner.

#### Reference to a related issue in the repository
Add a reference to a related issue in the repository.

- [X] I have performed a self-review of my own code.
- [ ] I have made corresponding changes to the [documentation](https://github.com/OpenSimulationInterface/osi-documentation).
- [X] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests / travis ci pass locally with my changes.

### CODE REVIEW

**Comment by tbleher** [comment]
@pmai und @jdsika : Ich weiß nicht, ob jemand von euch Mails bekommt von Pull-Requests hier, daher kurz ein Mention, dass ihr den Pull Request seht.

**Comment by jdsika** [comment]
I am in fact not subscribed :) thx for the mention

**Comment by tbleher** [comment]
@pmai and @jdsika : what needs to be done to get this pull request to be merged? Can you do this, or is there some ASAM process?

**Review by ThomasNaderBMW — APPROVED** [review]
I wasn't able to run it, because of missing OpenGL functions, but the build itself worked.
After a talk with @tbleher we think it is an improvement.
I would like to merge it in the next CCB (@kmeids ).

**Comment by kmeids** [comment]
**Output CBB 28.04.2021:**
1. @stefancyliax  will check out why travis did not run on this merge request.

**Comment by stefancyliax** [comment]
TravisCI did not run because of sercurity reasons as described here: https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions

Rebase for DCO is needed here. @ThomasNaderBMW

**Comment by tbleher** [comment]
So after a rebase, the change is now built successfully. Who can merge this now?

**Comment by ThomasNaderBMW** [comment]
Thank you @tbleher , too many topics as you know :/
I will care about the merge at the next CCB on 09.06.

**Comment by kmeids** [comment]
**Output CCB 09.06.2021:**
1. Checked by @ThomasNaderBMW and can be merged him as well.

**Pull request merged**
