### PR TITLE
Integrate fmu, field of view, and better alignment of the GUI fields.

### PR DESCRIPTION
**Pull request by Yang-Wu-Altran**
@pmai @CarloVanDriestenBMW  Sorry for this interrupt. There is small typo in the last Pull request. I remove it, and make this new one.
@pmai Could you please take care of the FMI library inside CMakeLists.txt ? Thanks very much!!

### CODE REVIEW

**Comment by CarloVanDriestenBMW** [comment]
@Yang-Wu-Altran you can just commit on an existing PR and you do not have to remove it all the time!

1) check out your branch locally
2) remove the typo (or anything else)
3) commit -m "fixed XYZ"
4) push

The changes will be visible for everyone.

**Comment by CarloVanDriestenBMW** [comment]
The FMU should be integrated via dependency to the other repository!

**Comment by pmai** [comment]
This commit seems do undo all of the changes I made to get this running, esp. for Travis CI, hence the breakage. So please change the commit to not do this.

@CarloVanDriestenBMW There should be no fixed dependency on the FMU, so no direct linkage between Repos is needed IMHO: Any FMU that is a Sensor FMU should work...

**Comment by Yang-Wu-Altran** [comment]
@pmai  Sorry for that. I am checking why it got undo all your changes. I think it's by accident.

**Comment by pmai** [comment]
The latest commit only seems to contain the makefile changes but not the include file breakage fixes (<osi/...> vs. „...“ which is the correct way).

**Comment by Yang-Wu-Altran** [comment]
@pmai  Could you please take a look at the error? "HTTP request sent, awaiting response... 404 Not Found" . Can not find jmodelica.org/download/...

**Comment by Yang-Wu-Altran** [comment]
@pmai  Thanks very much!

**Comment by CarloVanDriestenBMW** [comment]
@haoyuanying  abandon this one?

**Comment by haoyuanying** [comment]
@CarloVanDriestenBMW yes

**Pull request closed without merging**
