### PR TITLE
Updated osi-visualizer to handle ZMQ Push/Pull configuration in LiME

### PR DESCRIPTION
**Pull request by nreischl**

### CODE REVIEW

**Comment by CarloVanDriestenBMW** [comment]
Bump: @nreischl

I am back on Github again. Is this up-to-date?

**Comment by nreischl** [comment]
Up-to-date with the current LiME development.

**Comment by CarloVanDriestenBMW** [comment]
@pmai as discussed you are doing this and I #32

**Comment by vkresch** [comment]
Tested and works.

**Pull request merged**
